### ISSUE TITLE
[Proposal] adding IF NOT EXISTS in ossearch.sql

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimSearch#3]
To avoid errors during installation of ossearch.sql
I suggest to remplace all CREATE TABLE by CREATE TABLE IF NOT EXISTS

**Comment by kcozens** [comment]
commit 064b845bb63e8ac06a3ab796aec1ff296f34747c
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Fri Apr 21 15:11:04 2017 -0400

    Added IF NOT EXISTS to CREATE TABLE statements in ossearch.sql  (See issue #3)
