### ISSUE TITLE
Table regions is different in Grid Mode

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimSearch#4]
The regions table for OpenSim 0.9.0.1 in **Grid Mode** is different from your.

regions table from OpenSim **Grid Mode** is:

CREATE TABLE IF NOT EXISTS `regions` (
  `uuid` varchar(36) NOT NULL,
  `regionHandle` bigint(20) UNSIGNED NOT NULL,
  `regionName` varchar(128) DEFAULT NULL,
  `regionRecvKey` varchar(128) DEFAULT NULL,
  `regionSendKey` varchar(128) DEFAULT NULL,
  `regionSecret` varchar(128) DEFAULT NULL,
  `regionDataURI` varchar(255) DEFAULT NULL,
  `serverIP` varchar(64) DEFAULT NULL,
  `serverPort` int(10) UNSIGNED DEFAULT NULL,
  `serverURI` varchar(255) DEFAULT NULL,
  `locX` int(10) UNSIGNED DEFAULT NULL,
  `locY` int(10) UNSIGNED DEFAULT NULL,
  `locZ` int(10) UNSIGNED DEFAULT NULL,
  `eastOverrideHandle` bigint(20) UNSIGNED DEFAULT NULL,
  `westOverrideHandle` bigint(20) UNSIGNED DEFAULT NULL,
  `southOverrideHandle` bigint(20) UNSIGNED DEFAULT NULL,
  `northOverrideHandle` bigint(20) UNSIGNED DEFAULT NULL,
  `regionAssetURI` varchar(255) DEFAULT NULL,
  `regionAssetRecvKey` varchar(128) DEFAULT NULL,
  `regionAssetSendKey` varchar(128) DEFAULT NULL,
  `regionUserURI` varchar(255) DEFAULT NULL,
  `regionUserRecvKey` varchar(128) DEFAULT NULL,
  `regionUserSendKey` varchar(128) DEFAULT NULL,
  `regionMapTexture` varchar(36) DEFAULT NULL,
  `serverHttpPort` int(10) DEFAULT NULL,
  `serverRemotingPort` int(10) DEFAULT NULL,
  `owner_uuid` varchar(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `originUUID` varchar(36) DEFAULT NULL,
  `access` int(10) UNSIGNED DEFAULT '1',
  `ScopeID` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `sizeX` int(11) NOT NULL DEFAULT '0',
  `sizeY` int(11) NOT NULL DEFAULT '0',
  `flags` int(11) NOT NULL DEFAULT '0',
  `last_seen` int(11) NOT NULL DEFAULT '0',
  `PrincipalID` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `Token` varchar(255) NOT NULL,
  `parcelMapTexture` varchar(36) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
and your is:

CREATE TABLE `regions` (
  `regionname` varchar(255) NOT NULL,
  `regionuuid` char(36) NOT NULL,
  `regionhandle` varchar(255) NOT NULL,
  `url` varchar(255) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `owneruuid` char(36) NOT NULL,
  PRIMARY KEY  (`regionuuid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

If i use your, opensim don't work proprely, i have a warrning on the robust console.

**Comment by kcozens** [comment]
You are mixing up the database tables. The regions table used by the search module only contains six fields. The regions table in the main database used by OpenSimulator has a lot more fields. The search and profile modules must use a separate database from the databases used by the rest of Open Simulator.

**Comment by djphil** [comment]
We know that OpenSimSearch shares tables with OpenSimProfile (eg: classifieds).
We do not need to install opensim profile on separate database.
But we are obliged to install opensim search on separate database.

This is really confusing ...

Why, for example, do not call your regions table with a different name and thus allow to use opensim search on the same database as opensim? For example os_search_regions.

If really this is necessary, then finally i see that all the fields present in your regions.sql are also present in regions of opensim. Simply the names are different ...

Does your search module modify the table regions so that it becomes unusable for opensim?
If this is not the case, then why not just reflect the opensim regions table?

**Comment by kcozens** [comment]
In the installation part of the README files provided with the OpenSimSearch and OpenSimProfile modules it states that one of the first steps is setting up a database for use by the modules.

Entries in the main regions table are cleared when a region is shutdown. Entries in the regions table used by the search module persist even when the region is not running and are based on data parsed from running instances and whether regions/land are marked to be shown in search.

I have not changed the names of the tables used by these modules from what the original creator chose to use. The addon search and profile modules are meant to work together.

The core version of profile puts its tables in the main Open Simulator database. I have not tested the use of OpenSimSearch with the core profile module instead of the OpenSimProfile module.

**Comment by djphil** [comment]
I think this deserves reflection.
What is the best way to proceed.

Keep database of your Search and your Profile completely and obligatorily outside opensim database

or

Have the choice, on the same database as opensim or separately, without obligation.

Because yes as you say, some users will want to use built-in profile and will be bothered because classifield will not populated for your search module which is on separate database.

Another thing, you did not answer one of my questions.
I wanted to know if your search using regions table would break opensim regions table if we use the opensim default table (which is different from yours as reported).

If it does not break the opensim table, why not use it, it already exists!

**Comment by kcozens** [comment]
The search module needs a separate regions table. It will only have information on regions mentioned in the data generated by the Datasnapshot module. The main regions table used by Open Simulator is a list of all regions. Those regions may or may not have been flagged to show up in search results.
