### ISSUE TITLE
Multiple invalid field names in $query

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimSearch#5]
You have invalid field name on some request

exemple in parser.php:
$query = $db->prepare("DELETE FROM parcels WHERE regionuuid = ?");
shoud be:
$query = $db->prepare("DELETE FROM parcels WHERE regionUUID = ?");

or
$query = $db->prepare("DELETE FROM allparcels WHERE regionuuid = ?");
should be:
$query = $db->prepare("DELETE FROM allparcels WHERE regionUUID = ?");

And still others in parser.php

**Comment by kcozens** [comment]
commit 3a890f1b58ee718dccb405789cdd0af4cd0ea72b
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Fri Apr 21 14:45:54 2017 -0400

    Fixed case error in references to regionUUID field in several tables
