### ISSUE TITLE
data_exposure to all seam no working

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimSearch#8]
On my OpenSim 0.9.0.1 in Grid Mode, i set data_exposure to "all".
On the region i rez some objects with "show in search" checked and some without.
I refresh datas but i see only checked objects on the database "objects".
Seam to be a little bug ...

**Comment by kcozens** [comment]
Check the settings in the [DataSnapshot] section of your OpenSim.ini file. Most import is that you have "index_sims = true". Make sure you have a time set for default_snapshot_period that is greater than zero (but not too large while testing). Also check the URL you set for data_services. Make sure it points to the register.php file on your webserver.

You can check whether the datasnapshot module is working by entering a special URL in to a web browser. The form of the URL is: http://my.domain.name:port/?method=collector. Change my.domain.name to the domain name or IP address for the machine running regions. Check the regions table used by the search module to find the port address for a region with items marked to show in search. Your web browser will return XML data. If you don't see XML data you have a problem with the DataSnapshot module configuration.

**Comment by djphil** [comment]
Hello Plugh, you recently asked where this bug report was and you did well, I forgot this one.
So I did a check and all seem to be working fine on this. My initial configuration was correct.

I collected the data in 2 different ways:
- ?method=collector as you suggest 
- parser.php directly
Both work correctly.

Tested with the current php search and php 7.3
and 0.9.1.1 Dev 21 g435c30c: 2019-11-10 04:37

We can close this issue I think ...
Thanks to you!

**Comment by djphil** [comment]
Hello Plugh, you recently asked where we got to with this bug report and you did well, because I forgot this one.
So I checked and I confirm that there is a problem.

First I would like to clarify:
1) My initial configuration was correct.
2) I collected the data in 2 different ways:
- ?method=collector as you suggest
- parser.php directly (to collect datas in database)

Both work **but** the data is identical with
data_exposure = minimum or with data_exposure = all

Unless I am mistaken, "minimum" means only objects with "Show in search" checked, unlike "all" which means "expose everiything" (therefore also objects with "Show in search" **not** checked).

However my objects not checked remain absent from my database when I configured data_exposure on all

Tested with current php search and php 7.3
and with 0.9.1.1 Dev 21 g435c30c: 2019-11-10 04:37

**Comment by djphil** [comment]
**Steps to reproduce:**
1) set data_exposure to "minimum" in OpenSim.ini
2) create some objects on your region (some with "Show in search" checked and the others unchecked)
3) access to your page parse.php (http://server.com/search/paser.php)
4) Check the objects present in your "objects" database
5) Shutdown your simulator and set data_exposure to "all" in OpenSim.ini
6) Restart your simulator and access your parse.php page again.
7) Check again the objects present in your "objects" database

You should then see that there is no change.
minimum or all records exactly the same ...

**Comment by kcozens** [comment]
The parser.php file can only parse the data that was provided by the DataSnapshot module. If there is no difference in the data between using "minimum" or "all" for the data_exposure setting in OpenSim.ini you should file a bug against OpenSim.

**Comment by djphil** [comment]
http://opensimulator.org/mantis/view.php?id=8644

**Comment by kcozens** [comment]
Closing this report as invalid. The missing data is due to a problem in OpenSim per the mantis referenced in the previous comment.
