### ISSUE TITLE
IMPORTANT HELP

### ISSUE THREAD

**Issue by bimbam2103** [kcozens/OpenSimSearch#9]
Hello.

I try to setup a grid with searchfunction but i cannot get it working in 0.8.x or 0.9.x. Can you help me on how to setup searchfunction ?

Please feel free to contact me: c.nill@xs-project.de

Greetings

Christian Nill

**Comment by kcozens** [comment]
If you want to use it with 0.8 you need the dll from the 0.8.0-post-fixes branch. The dll in the master branch is for use with the 0.9 version of OpenSim. The rest of the information you need about setting up OpenSim to use the module is in the README file. If you need more help than that send a message to the OpenSimulator mailing list or ask in the #opensim-dev IRC channel.
